### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by KRASAB4IK123** [evildevill/instahack#18]
![IMG_20201126_174223](https://user-images.githubusercontent.com/75084137/100370462-fc917a80-300e-11eb-956b-2bfe2a881ee1.jpg)
What's going on?

**Comment by noenoughdata** [comment]
You Have To Activate Tor Service

**Comment by Nobody20369** [comment]
![Screenshot_20201208_162001](https://user-images.githubusercontent.com/75668726/101477804-bd035080-3975-11eb-88e0-c236fb2c37f4.png)

How to fix this 
Please help me bro

**Comment by noenoughdata** [comment]
@Nobody20369 I Wanted To Explain You Onething ,But It The Explanation Is Too Big,If You Got A Instagram Account,Message Me.
My Instagram Account- no_enough_data

Hope You Will Do

**Comment by evildevill** [comment]
@Nobody20369 
Watch this video it helps you a lot
https://cloudvideo.tv/6rllqe27f44l

**Comment by Nobody20369** [comment]
Thanks for your reply and help . Now its working ....:-):-)
Can you suggest me ...how to increase it's speed

**Comment by Nobody20369** [comment]
Sorry for a late response
But surely I will text you
My insta id :Nobody20369

**Comment by evildevill** [comment]
Use it's current speed if u increase this speed it gives error

**Comment by Nobody20369** [comment]
Ok...tq

**Comment by evildevill** [comment]
No need keep smile always 😊🖤🥰
