### ISSUE TITLE
![Screenshot_20201208_162001](https://user-images.githubusercontent.com/75668726/101477804-bd035080-3975-11eb-88e0-c236fb2c37f4.png)

### ISSUE THREAD

**Issue by Nobody20369** [evildevill/instahack#19]
![Screenshot_20201208_162001](https://user-images.githubusercontent.com/75668726/101477804-bd035080-3975-11eb-88e0-c236fb2c37f4.png)

How to fix this 
Please help me bro

_Originally posted by @Nobody20369 in https://github.com/evildevill/instahack/issues/18#issuecomment-740560800_

**Comment by evildevill** [comment]
I solved the problem you can visit my website and and read the full topic
about this tool and also watch video on my channel
*Video link :-*

*https://youtu.be/HEUSxFWZIsQ <https://youtu.be/HEUSxFWZIsQ>*

*MY Website link :-*

*https://rebrand.ly/hackerwasii <https://rebrand.ly/hackerwasii>*
