### ISSUE TITLE
After doing the $ bash setup, it stopped at bootstrap eventhough the percentage was already at 100 % and I can't continue the next command

### ISSUE THREAD

**Issue by 2ldane** [evildevill/instahack#22]
![ISsue Github](https://user-images.githubusercontent.com/76982780/104940930-ff906200-59e4-11eb-8d3b-674bf4cb0248.png)

**Comment by crackjuice** [comment]
I also have this problem

**Comment by evildevill** [comment]
@2ldane @crackjuice 
Just simply open new terminal and then type 
**_### bash instahack.sh_**
Also remembered if you close the first terminal then this tool isn't work properly...♥️

**Comment by crackjuice** [comment]
> @2ldane @crackjuice
> Just simply open new terminal and then type
> **_### bash instahack.sh_**
> Also remembered if you close the first terminal then this tool isn't work properly...♥️

Oh that makes sense now, thank you <3
