### ISSUE TITLE
I have a problem to use Instahack

### ISSUE THREAD

**Issue by mustafa13760806** [evildevill/instahack#25]
Hi
When i want to start TOR or bash INSTAHACK. SH these errors happen...
Please tell me how can I fix this problem?!
![Screenshot_20210213_021308](https://user-images.githubusercontent.com/75061017/107830561-5c432a80-6da1-11eb-98a9-e7cfbe7571f3.jpg)
![Screenshot_20210213_021255](https://user-images.githubusercontent.com/75061017/107830566-5e0cee00-6da1-11eb-91b2-b86224b9e2e8.jpg)

**Comment by evildevill** [comment]
@mustafa13760806 
Watch video on my website  🖤
https://hackerwasii.blogspot.com

**Comment by mustafa13760806** [comment]
I have problem to install TOR
Can u help or teach me how to install tor?

**Comment by mustafa13760806** [comment]
> @mustafa13760806
> Watch video on my website 🖤
> https://hackerwasii.blogspot.com

I have problem to install TOR
Can u help or teach me how to install tor?
