### ISSUE TITLE
fatal error:: Tor configuration invalid or server down :: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by VZLOMSHIKSAN4EK** [evildevill/instahack#26]
After selection..
[1] Auto Attack
[2] Manual Attack
[3] About
[4] Update                                            [5] Subscribe
[6] Chat now
[7] Follow
[8] Exit
                                                      [*] Choose an option:1
Further..
[#] User Name : name #######
[+] Type 1 FOR 1k Passwords
              [+] Type 2 FOR 10K Passwords
              [+] Type 3 FOR 1M Passwords

[#] Enter Selected Number:1
and after choosing it gives an error!

fatal error:: Tor configuration invalid or server down :: [Errno 111] Connection refused

but Instagram name is correct and exists...
help me please

**Comment by VZLOMSHIKSAN4EK** [comment]
Or am I doing something wrong?

**Comment by VZLOMSHIKSAN4EK** [comment]
or maybe I ran incorrectly tor then tell me how to start !!

**Comment by evildevill** [comment]
@VZLOMSHIKSAN4EK start tor in your new session or you can also watch video on my channel

**Comment by VZLOMSHIKSAN4EK** [comment]
![IMG_20210221_132614](https://user-images.githubusercontent.com/75779087/108623589-6e2f6800-7448-11eb-997d-1705b2724a5d.jpg)
![IMG_20210221_132624](https://user-images.githubusercontent.com/75779087/108623592-6f609500-7448-11eb-9066-cd3c25ec80fc.jpg)

tor I am running but for some reason again the error you know why?

**Comment by VZLOMSHIKSAN4EK** [comment]
The first screen is launched there tor

**Comment by evildevill** [comment]
@VZLOMSHIKSAN4EK 
Open new session and go to the instahack directory and type `tor` come back into the first terminal and type `bash`  `instahack.sh`
