### ISSUE TITLE
tell me why the passwords are the same?

### ISSUE THREAD

**Issue by VZLOMSHIKSAN4EK** [evildevill/instahack#30]
tell me why the passwords are the same, maybe I did something wrong?

**Comment by artest08** [comment]
The same problem also exists in my trials. I have also seen the same problem in solved issued but actually seems to be not solved or I cannot understand the answer

**Comment by evildevill** [comment]
@VZLOMSHIKSAN4EK 
@artest08 
Because you dont have an rooted device
