### ISSUE TITLE
fatal error:: Tor configuration invalid or server down

### ISSUE THREAD

**Issue by MrOdball** [evildevill/instahack#31]
when i executed instahack.sh i got this error 

"fatal error:: Tor configuration invalid or server down fatal error :: unable to use the control socket" 

My os :- ubuntu 18.04 (tor already installed and running )

Please, have a look thanks

**Comment by evildevill** [comment]
@MrOdball 
Open new terminal , Open instahack directory & then type ''''TOR'''

**Comment by MrOdball** [comment]
I think you didn't read everything tor already installed and running 
i am not using termux it's ubuntu 
Anyway I fixed it but i think apart trying to run from issues you should try to help others . . .
Thankyou
