### ISSUE TITLE
can anyone help me?

### ISSUE THREAD

**Issue by DaviDYzZ060** [evildevill/instahack#42]
[ Error : main/auto.sh file missing. Fix this error by getting the proper script file ]

**Comment by evildevill** [comment]
@DaviDYzZ060 

Try new update please☺️

**Comment by Babdram** [comment]
Help me

**Comment by evildevill** [comment]
> Help me

@Babdram 

What i help uh...

**Comment by Babdram** [comment]
من باید اکانت زنم چک‌ کنم

**Comment by evildevill** [comment]
@Babdram 

Can't understand your language 😐

**Comment by Babdram** [comment]
Iwant chek my husband accounts Instagram or Whatssapp
