### ISSUE TITLE
The payment is ready

### ISSUE THREAD

**Issue by KRO2311** [evildevill/instahack#51]
How i get the pass?

**Comment by theelinuxchoice** [comment]
Activation key is send to your email address when payment is successful

**Comment by KRO2311** [comment]
I can't see the key, maybe is an error?

**Comment by KRO2311** [comment]
![Screenshot_20210831-014615_Gmail](https://user-images.githubusercontent.com/89817011/131449410-1c1e3d43-842b-4aef-85ea-101d4ce2a4db.jpg)

**Comment by evildevill** [comment]
If you already sent the payment then give your transaction ID

**Comment by KRO2311** [comment]
2UH10821555548618 transaction ID

Benjamin2001caro@gmail.com is my email adress

**Comment by theelinuxchoice** [comment]
Ok fine

The money you send to me goes hold. Here's the step you need to follow
kindly. Follow these steps to confirm your payment and then I'll provide
you the activation key of instahack


Here's How to Confirm that you have received the item.

1) Go to www.paypal.com and log into your account
2) Click Activity
3) Find and click the payment that you have send to me. Open it
4) Here you see Click confirm Receipt
5) Click yes to confirm that you have received the order.

Once you confirm the Payment then send the screen shot and transaction ID
then I'll provide you an activation key.

Thanks in Advance 🙃.
